services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - alejhernet
    depends_on:
      - wordpress
      
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - alejhernet
  
  ftp:
    build: ./requirements/ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - alejhernet
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - alejhernet
    depends_on:
      - mariadb
      - redis

  static:
    build: ./requirements/static
    container_name: static
    restart: always
    ports:
      - "8080:80"
    networks:
      - alejhernet
  
  redis:
    build: ./requirements/redis
    container_name: redis
    restart: always
    networks:
      - alejhernet
  
  adminer:
    build: ./requirements/adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - alejhernet
    depends_on:
      - mariadb

networks:
  alejhernet:
    driver: bridge

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            device: /home/alejhern/data/mariadb
            o: bind

    wordpress_data:
        driver: local
        driver_opts:
            type: none
            device: /home/alejhern/data/wordpress
            o: bind